version: '3.2'
services:
  backend1:
    build: ./backend
    restart: unless-stopped
    networks:
      - app-net

  backend2:
    build:
      context: ./backend
    restart: unless-stopped
    networks:
      - app-net

  loadbalancer:
    build: ./load-balancer
    ports:
      - "80:80"
    depends_on:
      - backend1
      - backend2
    restart: unless-stopped
    networks:
      - app-net

networks:
  app-net:
    driver: bridge